FROM thijs/php:alpine-php-7.4

RUN \
 echo "**** install runtime packages ****" && \
 apk add --no-cache --upgrade \
    logrotate \
    nginx && \
    rm -rf /tmp/* && \
 echo "**** configure nginx ****" && \
 echo 'fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;' >> \
	/etc/nginx/fastcgi_params && \
 rm -f /etc/nginx/conf.d/default.conf && \
 echo "**** fix logrotate ****" && \
 sed -i "s#/var/log/messages {}.*# #g" /etc/logrotate.conf && \
 sed -i 's#/usr/sbin/logrotate /etc/logrotate.conf#/usr/sbin/logrotate /etc/logrotate.conf -s /config/log/logrotate.status#g' \
	/etc/periodic/daily/logrotate

# add local files
COPY files/ /

# ports and volumes
EXPOSE 80 443

VOLUME /config