version: "3.7"

services:
  core:
    image: thijs/phabricator:latest
    ports:
      - "22:22/tcp"
      - "80:80/tcp"
    links:
      - database
  database:
    image: mysql:5.7
    ports:
      - "3306:3306/tcp"
    environment: 
      - MYSQL_ROOT_PASSWORD=root